version: '3'

services:
  zap2xml:
    image: shuaiscott/zap2xml:latest
    restart: always
    volumes:
        - ~/Docker/mac/zap2xml/:/data
    environment:
        - USERNAME=olavpovo@gmail.com
        - PASSWORD=Aa629415
        - OPT_ARGS=-I -D
        - XMLTV_FILENAME=iptv.xml
